on:
  workflow_dispatch:
    inputs:
      firmware_url:
        description: 'URL to the AP firmware file (direct download link)'
        required: true

jobs:
  inspect:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Create Directories
        run: |
          mkdir download extracted output

      - name: 2. Download Firmware
        run: |
          echo "Downloading from ${{ github.event.inputs.firmware_url }}..."
          wget -O download/firmware.zip "${{ github.event.inputs.firmware_url }}"

      - name: 3. Unzip Archive
        run: |
          echo "Unzipping outer archive..."
          unzip download/firmware.zip -d extracted

      - name: 4. Untar Inner .tar.md5 Archive
        run: |
          echo "Unpacking inner .tar.md5 file(s)..."
          find extracted -name '*.tar.md5' -exec tar -xf {} -C extracted \;

      - name: 5. List All Extracted Files
        run: |
          echo "Creating full file list..."
          ls -lR extracted > output/full_file_list.txt

      - name: 6. Filter GPU-Related Blobs
        run: |
          echo "Filtering for firmware, egl, vulkan, gralloc, .so, .bin, .fw..."
          grep -iE "firmware|egl|vulkan|gralloc|\.so$|\.bin$|\.fw$" output/full_file_list.txt > output/gpu_blobs_list.txt
          echo "Filtered list saved to output/gpu_blobs_list.txt"

      - name: 7. Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: firmware-inspection-results
          path: output/
